name: install from staging

on:
  push:
    branches: [ staging ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Test install and run
        run:
          cd integration_tests/install_from_dev_branch
          ./test.sh
