name: integration

on: [workflow_dispatch]

jobs:
  integration-test:
    needs: [ to-master ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Test install and run
        run:
          cd integration
          ./test.sh
